---

title: "Kardex"
author: "Luz Neydy Lavariega Enriquez"
date: "29 de agosto de 2016"
output: html_document:
    theme: cerulean
---

## Otoño 2013

### Lista de materias
* Introduccion a la Profesion actuarial 7
* DHPC 10
* Conceptos de calculo 7
* Matematicas basicas 7
* Problemas de matematicas basicas 7

## Primavera 2014

### Lista de materias
* Programacian actuarial I 8
* Microeconomaa 10
* Formacian humana y social 8
* Teoria del interes 8

## Otoño 2014

### Lista de materias
* Macroeconomia 8
* Lengua extrangera I 10
* Lengua extrangera II 10 
* Calculo diferencial 8
* Teoraa de ecuaciones 10

## Primavera 2014

### Lista de materias
* Teroria del interes II 8
* DHTICS 9
* Lengua extrangera III 9
* Calculo integral 7
* Algebra lineal 8

## Otoño 2015

### Lista de materias
* Programacion actuarial II 9
* Sistema financiero mexicano 10
* Demografia 7
* Ecuaciones diferenciales I 8

## Primavera 2016

### Lista de materias
* Contabilidad general 8
* Matematicas actuariales I 8
* Derivados financieros 9
* Registros academicos y cientificos del español 9
* Calculo diferencial en varias variables 9
